ExcelOutput = {
    type: "Roles",
    title: "User access definitions for inbox editor",
    AccessDefinition: {
        GlobalAccess: {
            AllowedUsers: ['KGOPINAT','PSRINIV1','MALI2', 'AMADHUSU', 'MSANKARA', 'MREDDY1', 'BGOUDAR', 'PMAKENA', 'SPATIL1'],
            AllowedUsersFullName: []
        },
        InboxLevelAccess: {
			NewObj1 : "new obj1",
InboxDistributionWarehouseMonitorOutboundTU: { AllowedUsers: ["SDURAIRA"] },
InboxDistributionWarehouseMonitorAssignedDeliveries: { AllowedUsers: ["SDURAIRA"] },
InboxDistributionWarehouseMonitorOutboundDeliveryItems: { AllowedUsers: ["SDURAIRA"] },
InboxDistributionWarehouseMonitorAssignedDoors: { AllowedUsers: ["SDURAIRA"] },
InboxDistributionWarehouseMonitorChildHU: { AllowedUsers: ["SDURAIRA"] },
InboxDistributionWarehouseMonitorOutboundWaves: { AllowedUsers: ["SDURAIRA"] },
InboxDistributionWarehouseMonitorOutboundDelivery: { AllowedUsers: ["SDURAIRA"] },
InboxDistributionWarehouseMonitorOutboundDeliveryTexts: { AllowedUsers: ["SDURAIRA"] },
InboxDistributionWarehouseMonitorPSHU: { AllowedUsers: ["SDURAIRA"] },
InboxDistributionWarehouseMonitorOutboundChildHU: { AllowedUsers: ["SDURAIRA"] },
InboxDistributionWarehouseMonitorOutboundDeliveriesWaves: { AllowedUsers: ["SDURAIRA"] },
InboxDistributionWarehouseMonitorMaterialDocuments: { AllowedUsers: ["SDURAIRA"] },
InboxDistributionWarehouseMonitorOutboundSTO: { AllowedUsers: ["SDURAIRA"] },
InboxDistributionWarehouseMonitorOutboundHU: { AllowedUsers: ["SDURAIRA"] },
InboxDistributionWarehouseMonitorOutboundHUDeliveries: { AllowedUsers: ["SDURAIRA"] },
InboxDistributionWarehouseMonitorOutboundHUContent: { AllowedUsers: ["SDURAIRA"] },
InboxDistributionWarehouseMonitorOutboundVendorReturns: { AllowedUsers: ["SDURAIRA"] },
InboxDistributionWarehouseMonitorOutboundCustomer: { AllowedUsers: ["SDURAIRA"] },
InboxDistributionWarehouseMonitorOutboundCartonizationPlanning: { AllowedUsers: ["SDURAIRA"] },
InboxDistributionWarehouseMonitorWaves: { AllowedUsers: ["SDURAIRA"] },
InboxDistributionWarehouseMonitorWaveItem: { AllowedUsers: ["SDURAIRA"] },
InboxDistributionWarehouseMonitorOutboundWOs: { AllowedUsers: ["SDURAIRA"] },
InboxDistributionWarehouseMonitorWarehouseTask: { AllowedUsers: ["SDURAIRA"] },
InboxDistributionWarehouseMonitorOutboundWTs: { AllowedUsers: ["SDURAIRA"] },
InboxDistributionWarehouseMonitorInboundTU: { AllowedUsers: ["SSINGH4"] },
InboxDistributionWarehouseMonitorInboundDelivery: { AllowedUsers: ["SSINGH5"] },
InboxDistributionWarehouseMonitorInboundAssignedDeliveriyItem: { AllowedUsers: ["SSINGH6"] },
InboxDistributionWarehouseMonitorInboundHU: { AllowedUsers: ["SSINGH7"] },
InboxDistributionWarehouseMonitorInboundDeliveryTexts: { AllowedUsers: ["SSINGH11"] },
InboxDistributionWarehouseMonitorInboundASN: { AllowedUsers: ["SSINGH15"] },
InboxDistributionWarehouseMonitorInboundExternalPO: { AllowedUsers: ["SSINGH20"] },
InboxDistributionWarehouseMonitorInboundSTO: { AllowedUsers: ["SSINGH25"] },
InboxDistributionWarehouseMonitorInboundVendor: { AllowedUsers: ["SSINGH31"] },
InboxDistributionWarehouseMonitorInboundCustomerReturns: { AllowedUsers: ["SSINGH36"] },
InboxDistributionWarehouseMonitorInboundWOs: { AllowedUsers: ["SSINGH41"] },
InboxDistributionWarehouseMonitorInboundWTs: { AllowedUsers: ["SSINGH42"] },
InboxDistributionPhysicalInventory: { AllowedUsers: ["VNATESAN"] },
InboxDistributionProduct: { AllowedUsers: ["VNATESAN"] },
InboxDistributionWarehouseMonitorProductByBin: { AllowedUsers: ["VNATESAN"] },
InboxDistributionWarehouseMonitorProductHandlingUnit: { AllowedUsers: ["VNATESAN"] },
InboxDistributionWarehouseMonitorBin: { AllowedUsers: ["VNATESAN"] },
InboxDistributionWarehouseMonitorBinInboundWarehouseTask: { AllowedUsers: ["VNATESAN"] },
InboxDistributionWarehouseMonitorBinOutboundWarehouseTask: { AllowedUsers: ["VNATESAN"] },
InboxDistributionStockAccuracy: { AllowedUsers: ["VNATESAN"] },
InboxDistributionInternalPlantStock: { AllowedUsers: ["VNATESAN"] },
InboxDistributionWarehouseOrder: { AllowedUsers: ["VNATESAN"] },
InboxDistributionWarehouseTask: { AllowedUsers: ["VNATESAN"] },
InboxDistributionPostingChanges: { AllowedUsers: ["VNATESAN"] },
InboxDistributionInternalHandlingUnits: { AllowedUsers: ["VNATESAN"] },
InboxDistributionReturnablesTracking: { AllowedUsers: ["VNATESAN"] },
InboxDistributionWorkload: { AllowedUsers: ["VNATESAN"] },
InboxDistributionPackerPackingStation: { AllowedUsers: ["GMITTAL"] },
InboxDistributionPackerHandlingUnit: { AllowedUsers: ["GMITTAL"] },
InboxDistributionPackerProductsandInstructions: { AllowedUsers: ["GMITTAL"] },
InboxProductStagingPMRSingleOrder: { AllowedUsers: ["SPRAKAS6"] },
InboxProductStagingPMRSingleOrderComponents: { AllowedUsers: ["SPRAKAS5"] },
InboxProductStagingPMRCrossOrder: { AllowedUsers: ["SPRAKAS3"] },
InboxProductStagingCollectiveStaging: { AllowedUsers: ["SPRAKAS1"] },
InboxProductStagingDecanting: { AllowedUsers: ["SPRAKAS0"] },
InboxProductStagingStagingOverview: { AllowedUsers: ["SPRAKAS1"] },
InboxProductStagingPantryReplinshmentRequirement: { AllowedUsers: ["VNATESAN"] },
InboxProductStagingProcessOrderComponent: { AllowedUsers: ["VNATESAN"] },
InboxProductStagingPantryStagingRequest: { AllowedUsers: ["VNATESAN"] },
InboxProductStagingStockAvailability: { AllowedUsers: ["VNATESAN"] },
InboxProductStagingWarehouseTask: { AllowedUsers: ["VNATESAN"] },
InboxProductStagingPantryReplinshmentOpenWarehouseTask: { AllowedUsers: ["VNATESAN"] },
InboxDistributionPickingMonitorDelivery: { AllowedUsers: ["PALPHA"] },
InboxDistributionPickingMonitorDeliveryPSHU: { AllowedUsers: ["PALPHA"] },
InboxDistributionPickingMonitorWaves: { AllowedUsers: ["PALPHA"] },
InboxDistributionPickingMonitorWareHouseOrder: { AllowedUsers: ["PALPHA"] },
InboxDistributionShippingAndReceivingOutboundTU: { AllowedUsers: ["SDURAIRA"] },
InboxDistributionShippingAndReceivingAssignedDeliveries: { AllowedUsers: ["SDURAIRA"] },
InboxDistributionShippingAndReceivingOutboundDeliveryItems: { AllowedUsers: ["SDURAIRA"] },
InboxDistributionShippingAndReceivingAssignedDoors: { AllowedUsers: ["SDURAIRA"] },
InboxDistributionShippingAndReceivingChildHU: { AllowedUsers: ["SDURAIRA"] },
InboxDistributionShippingAndReceivingOutboundWaves: { AllowedUsers: ["SDURAIRA"] },
InboxDistributionShippingAndReceivingOutboundDelivery: { AllowedUsers: ["SDURAIRA"] },
InboxDistributionShippingAndReceivingOutboundDeliveryTexts: { AllowedUsers: ["SDURAIRA"] },
InboxDistributionShippingAndReceivingPSHU: { AllowedUsers: ["SDURAIRA"] },
InboxDistributionShippingAndReceivingOutboundChildHU: { AllowedUsers: ["SDURAIRA"] },
InboxDistributionShippingAndReceivingOutboundDeliveriesWaves: { AllowedUsers: ["SDURAIRA"] },
InboxDistributionShippingAndReceivingMaterialDocuments: { AllowedUsers: ["SDURAIRA"] },
InboxDistributionShippingAndReceivingOutboundSTO: { AllowedUsers: ["SDURAIRA"] },
InboxDistributionShippingAndReceivingOutboundHU: { AllowedUsers: ["SDURAIRA"] },
InboxDistributionShippingAndReceivingOutboundHUDeliveries: { AllowedUsers: ["SDURAIRA"] },
InboxDistributionShippingAndReceivingOutboundHUContent: { AllowedUsers: ["SDURAIRA"] },
InboxDistributionShippingAndReceivingOutboundCustomer: { AllowedUsers: ["SDURAIRA"] },
InboxDistributionShippingAndReceivingOutboundVendorReturns: { AllowedUsers: ["SDURAIRA"] },
InboxDistributionShippingAndReceivingInboundTU: { AllowedUsers: ["SSINGH34"] },
InboxDistributionShippingAndReceivingInboundDelivery: { AllowedUsers: ["SSINGH33"] },
InboxDistributionShippingAndReceivingInboundAssignedDeliveriyItem: { AllowedUsers: ["SSINGH32"] },
InboxDistributionShippingAndReceivingInboundHU: { AllowedUsers: ["SSINGH31"] },
InboxDistributionShippingAndReceivingInboundASN: { AllowedUsers: ["SSINGH23"] },
InboxDistributionShippingAndReceivingInboundExternalPO: { AllowedUsers: ["SSINGH18"] },
InboxDistributionShippingAndReceivingInboundSTO: { AllowedUsers: ["SSINGH13"] },
InboxDistributionShippingAndReceivingInboundVendor: { AllowedUsers: ["SSINGH7"] },
InboxDistributionShippingAndReceivingInboundCustomerReturns: { AllowedUsers: ["SSINGH2"] },
InboxDistributionTrackingandvisibilityOTCTracking: { AllowedUsers: ["MSEN3"] },
InboxDistributionTrackingandvisibilityOTCLineItems: { AllowedUsers: ["MSEN2"] },
InboxDistributionTrackingandvisibilityReturnables: { AllowedUsers: ["MSEN1"] },
InboxDistributionTrackingandvisibilityP2P: { AllowedUsers: ["MSEN0"] },
InboxDistributionTransportationPlannerFreightUnit: { AllowedUsers: ["ABISWAS"] },
InboxDistributionTransportationPlannerFreightOrder: { AllowedUsers: ["ABISWAS"] },
InboxDistributionTransportationPlannerCarrier: { AllowedUsers: ["ABISWAS"] },
InboxDistributionTransportationPlannerResource: { AllowedUsers: ["ABISWAS"] },
InboxDistributionTransportationPlannerCustomer: { AllowedUsers: ["ABISWAS"] },
InboxDistributionTransportationPlannerRequirement: { AllowedUsers: ["ABISWAS"] },
InboxDistributionTransportationExecutionFreightOrders: { AllowedUsers: ["ABISWAS"] },
InboxDistributionTransportationExecutionProducts: { AllowedUsers: ["ABISWAS"] },
InboxDistributionTransportationExecutionCarrier: { AllowedUsers: ["ABISWAS"] },
InboxDistributionTransportationExecutionCustomers: { AllowedUsers: ["ABISWAS"] },
InboxDistributionTransportationExecutionLocations: { AllowedUsers: ["ABISWAS"] },
InboxDistributionGlobalTradeBlockedDocument: { AllowedUsers: ["SSWAMI"] },
InboxDistributionGlobalCustomsClearanceChildDocumentItems: { AllowedUsers: ["SSWAMI"] },
InboxDistributionGlobalCustomsClearanceChildLegalRegulations: { AllowedUsers: ["SSWAMI"] },
InboxDistributionGlobalCustomsClearanceLicenseType: { AllowedUsers: ["SSWAMI"] },
InboxDistributionGlobalCustomsClearanceReviewDocuments: { AllowedUsers: ["SSWAMI"] },
InboxDistributionGlobalCustomsClearanceLegalRegulations: { AllowedUsers: ["SSWAMI"] },
InboxDistributionGlobalTradeBusinessPartner: { AllowedUsers: ["SSWAMI"] },
InboxDistributionGlobalTradeOrgStructure: { AllowedUsers: ["SSWAMI"] },
InboxDistributionGlobalTradeProductClassification: { AllowedUsers: ["SSWAMI"] }
		}
	}
}
